name: Deploy Java Project

on:
  push:
    branches: [ main ]  # Change to your desired branch(es)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Adjust the runner OS if needed

    steps:
      - uses: actions/checkout@v3  # Checkout project code

      # Configure Terraform (store credentials as secrets)
      - name: Login to AWS (replace with your provider)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1  # Replace with your desired region

      # Run Terraform init, plan, and apply
      - name: Initialize Terraform
        run: terraform init -backend-config=backend.tfvars

      - name: Run Terraform plan
        run: terraform plan

      - name: Apply Terraform changes (approval might be needed)
        run: terraform apply -auto-approve

      # Deploy Java project with Ansible
      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Deploy with Ansible
        run: ansible-playbook -i ./iac/inventory.yml ./ansible/playbook.yml
